/*
items = [];
jQuery('#thumbnails .item a').each(function(i,item){
    items.push({
        filename:jQuery(item).attr('href').substr(7),
        color: 'red'});
});
console.info(JSON.stringify(items));
*/
galeryManager.createAlbumCategory('tulpen-2015', 'fotografie|blumen|tulpe', [
    {
        "filename": "DSCF001-5884.jpg",
        "color": "red"
    }, {
        "filename": "DSCF1529.JPG",
        "color": "red"
    }, {
        "filename": "DSCF1530.JPG",
        "color": "red"
    }, {
        "filename": "DSCF1537.JPG",
        "color": "red"
    }, {
        "filename": "DSCF1539.JPG",
        "color": "red"
    }, {
        "filename": "DSCF1545.JPG",
        "color": "red"
    }, {
        "filename": "DSCF3227.JPG",
        "color": "red"
    }, {
        "filename": "DSCF1553.JPG",
        "color": "red"
    }, {
        "filename": "DSCF1572.JPG",
        "color": "red"
    }, {
        "filename": "DSCF1573.JPG",
        "color": "red"
    }, {
        "filename": "DSCF1575-taken.JPG",
        "color": "red"
    }, {
        "filename": "DSCF1577.JPG",
        "color": "red"
    }, {
        "filename": "DSCF7982.JPG",
        "color": "red"
    }, {
        "filename": "DSCF7983.JPG",
        "color": "red"
    }, {
        "filename": "DSCF7984.JPG",
        "color": "red"
    }, {
        "filename": "DSCF7985.JPG",
        "color": "red"
    }, {
        "filename": "DSCF7986.JPG",
        "color": "red"
    }, {
        "filename": "DSCF7987.JPG",
        "color": "red"
    }, {
        "filename": "DSCF7988.JPG",
        "color": "red"
    }, {
        "filename": "DSCF7989.JPG",
        "color": "red"
    }, {
        "filename": "DSCF7990.JPG",
        "color": "red"
    }, {
        "filename": "DSCF7981.JPG",
        "color": "red"
    }, {
        "filename": "DSCF8009.JPG",
        "color": "red"
    }, {
        "filename": "DSCF8010.JPG",
        "color": "red"
    }, {
        "filename": "DSCF8003.JPG",
        "color": "red"
    }, {
        "filename": "DSCF8004.JPG",
        "color": "red"
    }, {
        "filename": "DSCF8005.JPG",
        "color": "red"
    }, {
        "filename": "DSCF8006.JPG",
        "color": "red"
    }, {
        "filename": "DSCF8007.JPG",
        "color": "red"
    }, {
        "filename": "DSCF8008.JPG",
        "color": "red"
    }, {
        "filename": "DSCF1579.JPG",
        "color": "red"
    }, {
        "filename": "DSCF1580.JPG",
        "color": "red"
    }, {
        "filename": "DSCF1598_nice.JPG",
        "color": "red"
    }, {
        "filename": "DSCF1599.JPG",
        "color": "red"
    }, {
        "filename": "DSCF1609.JPG",
        "color": "red"
    }, {
        "filename": "DSCF1610.JPG",
        "color": "red"
    }, {
        "filename": "DSCF1611.JPG",
        "color": "red"
    }, {
        "filename": "DSCF1612.JPG",
        "color": "red"
    }, {
        "filename": "DSCF1623.JPG",
        "color": "red"
    }, {
        "filename": "DSCF1624.JPG",
        "color": "red"
    }
]);
